# installation prometheus avec docker

FROM ubuntu/prometheus:latest

#RUN wget https://packages.ubuntu.com/jammy/apt-offline

RUN apt update
RUN sudo apt install libfuse2
RUN apt install mc
RUN apt install ubuntu-restricted-extras
RUN apt apt install ubuntu-restricted-extras
  

RUN apt add sudo -y


RUN apt add openssh-client 
