# dans ce fichier nous avons parametré des exemples de  relabel et des metric_relabel

global:
  scrape_interval:     15s
  evaluation_interval: 15s

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
      monitor: 'docker-host-alpha'

# Load and evaluate rules in this file every 'evaluation_interval' seconds.
rule_files:
  - "alert.rules"

# A scrape configuration containing exactly one endpoint to scrape.
scrape_configs:
  - job_name: 'nodeexporter'
    scrape_interval: 5s
    static_configs:
      - targets: ['nodeexporter:9100']
    relabel_configs: 
      - source_label: [_address_]
        regex: '192.168(.*)'
        action: drop
#   metric_relabel_configs:
#     - source_labels: [_name_]
#     regex: '(node_load1|node load15)'
#     action: keep    
  - job_name: 'cadvisor'
    scrape_interval: 5s
- job_name: 'cadvisor'                                                    
    scrape_interval: 5s                                         
    static_configs:                                                        
      - targets: ['cadvisor:8080']                                         
                                  
  - job_name: 'prometheus'                                                 
    scrape_interval: 10s                                           
    static_configs:                                                
      - targets: ['localhost:9090']   
                                                                   
  - job_name: 'pushgateway'       
    scrape_interval: 10s              
    honor_labels: true                  
    static_configs:                     
      - targets: ['pushgateway:9091']   
                           alerting:                                                                  
  alertmanagers:                                                           
  - scheme: http                  
    static_configs:                                                        
    - targets:                                                     
      - 'alertmanager:9093'                                        
                                      
#  - job_name: 'nginx'                                             
#    scrape_interval: 10s         
#    static_configs:                  
#      - targets: ['nginxexporter:9113']
                                        
#  - job_name: 'aspnetcore'             
#    scrape_interval: 10s               
#    static_configs:                    
#      - targets: ['eventlog-proxy:5000', 'eventlog:5000']
