version: '3'
services:
  netdata:
    image: netdata/netdata:edge
    container_name: netdata
    hostname: example.com # set to fqdn of host
    ports:
      - 19999:19999
    restart: unless-stopped
    cap_add:
      - SYS_PTRACE
    security_opt:
      - apparmor:unconfined
    volumes:
      - netdataconfig:/etc/netdata
      - netdatalib:/var/lib/netdata
      - netdatacache:/var/cache/netdata
      - /etc/passwd:/host/etc/passwd:ro
      - /etc/group:/host/etc/group:ro
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /etc/os-release:/host/etc/os-release:ro
    environment:
      - NETDATA_CLAIM_TOKEN=l8QbOLfUqmzgDSEwWVzL3qlbkKuw2LG-5jQcpB-u9zzXuG5a9xGlF3kjvpplcyB9_t4odff_TbcTIBgZxSz9zRsXEda-QyyFVOKlwlq0y0gPZbtnHXqWenp6xXQsTKLablsIRq0
      - NETDATA_CLAIM_URL=https://app.netdata.cloud
      - NETDATA_CLAIM_ROOMS=

volumes:
  netdataconfig:
  netdatalib:
  netdatacache:
